version: '3.8'
services:
  cartservice:
    image: cartservice:latest
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-container:3306/cart
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: ticketing
    depends_on:
      - mysql-container

  mysql-container:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ticketing
      MYSQL_DATABASE: cart
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
