FROM node:18

# Create app directory
WORKDIR /usr/src/app

# Install app dependencies
COPY package*.json ./

RUN npm install

# Rebuild bcrypt for the correct platform
RUN npm rebuild bcrypt --build-from-source



# Bundle app source
COPY . .

EXPOSE 3000
CMD ["npm","start"]

# Define environment variable for the database password
ENV DB_PASSWD=bbNs1QyBqy7Kzwn7
ENV JWT_SECRET=mySecret
# Start the application
CMD ["node", "index.js"]
