version: '3'

services:
  user-service:
    build: .
    ports:
      - "3000:3000"
    environment:

      DB_PASSWD: bbNs1QyBqy7Kzwn7
      JWT_SECRET: mySecret
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
