# Use the official Node.js 16 image as the base
FROM node:16

# Set the working directory in the container
WORKDIR /app

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code to the working directory
COPY . .

# Expose the port the app runs on
EXPOSE 3000

# Define environment variable for the database password
ENV DB_PASSWD=bbNs1QyBqy7Kzwn7
ENV JWT_SECRET=mySecret
# Start the application
CMD ["node", "index.js"]
