
# Use the official Node.js 16 image as the base
FROM node:18

# Create app directory
WORKDIR /usr/src/app

# Install app dependencies
COPY package*.json ./

RUN npm install

# Rebuild bcrypt for the correct platform
RUN npm rebuild bcrypt --build-from-source



# Bundle app source
COPY . .

EXPOSE 8084
CMD ["npm","start"]

# Start the application
CMD ["node", "index.js"]
